name:                quizify
version:             0.1
github:              "https://github.com/DoctorRyner/quizify"

dependencies:
- base >= 4.7 && < 5

executables:
  quizify-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N